# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan's Blog
email: jon@blazorapps.io
description: > # this means to ignore newlines until "baseurl:"
  Some of my current interests reading Juval Lowy's new book Righting Software, Kubernetes, gRPC, Angular, React, Blazor and functional programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blazorapps.io" # the base hostname & protocol for your site
twitter_username: jonathanparker
github_username:  jonparker
permalink: pretty
# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
