# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan's Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some of my current interests include Kubernetes, gRPC, React, Blazor and functional programming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonparker.github.io.com" # the base hostname & protocol for your site
twitter_username: jonathanparker
github_username:  jonparker
permalink: pretty
# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
